# Generated by Django 2.2.4 on 2019-09-22 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('last_name', models.CharField(max_length=100, verbose_name='sobrenome')),
                ('registration', models.CharField(max_length=10, unique=True, verbose_name='matricula')),
                ('sex', models.CharField(choices=[('MAS', 'Masculino'), ('FEM', 'Feminino'), ('OUT', 'Outros')], default='Masculino', max_length=3, verbose_name='sexo')),
                ('date_birth', models.DateField(verbose_name='data_nasc')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
            ],
            options={
                'verbose_name_plural': 'alunos',
            },
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('last_name', models.CharField(max_length=100, verbose_name='sobrenome')),
            ],
            options={
                'verbose_name_plural': 'autores',
            },
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='titulo')),
                ('year_publication', models.IntegerField(verbose_name='ano_publicacao')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appemprestimo.Autor')),
            ],
            options={
                'verbose_name_plural': 'livros',
            },
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_withdrawn', models.DateField(verbose_name='data_retirada')),
                ('date_devolution', models.DateField(verbose_name='data_devolucao')),
                ('returned', models.BooleanField(verbose_name='devolvido')),
                ('books', models.ManyToManyField(to='appemprestimo.Livro')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appemprestimo.Aluno')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'emprestimos',
            },
        ),
    ]
